### ISSUE TITLE
Practica 11

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-proyecto-contrato-inteligente-awua-de-limon#1]
[Practica. 11.pdf](https://github.com/user-attachments/files/18056641/Practica.11.pdf)

**Comment by Arlet04** [comment]
Cumple con portada y los escudos institucionales: 25 puntos
Describe los objetivos de la practica: 25 puntos
Describe el procedimiento: 25 puntos
Muestra resultados y conclusiones: 25 puntos
Puntaje alcanzado 100% = 50 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
